services:
  - type: web
    name: smart-agri
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: AFRICASTALKING_API_KEY
        sync: false
      - key: AFRICASTALKING_USERNAME
        sync: false
      - key: AFRICASTALKING_SANDBOX
        value: "True"
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: smart-agri-db
          property: connectionString

databases:
  - name: smart-agri-db
    databaseName: smart_agri
    user: smart_agri_user 